Web/src/AppBundle/Entity/Comment.php
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use UserBundle\Entity\User;
/**
 * Comment
 *
 * @ORM\Table(name="comment_table")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\CommentRepository")
 */
class Comment
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;
    
    /**
     * @var string
     *
     * @ORM\Column(name="content", type="text")
     */
    private $content;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="created", type="datetime")
     */
    private $created;

    /**
     * @var bool
     *
     * @ORM\Column(name="enabled", type="boolean")
     */
    private $enabled;







        /**
     * @ORM\ManyToOne(targetEntity="Video", inversedBy="comments")
     * @ORM\JoinColumn(name="video_id", referencedColumnName="id", nullable=true)
     */
    private $video;




    /**
     * @ORM\ManyToOne(targetEntity="UserBundle\Entity\User", inversedBy="comments")
     * @ORM\JoinColumn(name="user_id", referencedColumnName="id", nullable=false)
     */
    private $user;
    public function __construct()
    {
        $this->created= new \DateTime();

    }
    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }



    /**
     * Set content
     *
     * @param string $content
     * @return Comment
     */
    public function setContent($content)
    {
        $this->content = $content;

        return $this;
    }

    /**
     * Get content
     *
     * @return string 
     */
    public function getContent()
    {
        return $this->content;
    }
    public function getContentclear()
    {
        return base64_decode($this->content);
    }
    /**
     * Set created
     *
     * @param \DateTime $created
     * @return Comment
     */
    public function setCreated($created)
    {
        $this->created = $created;

        return $this;
    }

    /**
     * Get created
     *
     * @return \DateTime 
     */
    public function getCreated()
    {
        return $this->created;
    }

    /**
     * Set enabled
     *
     * @param boolean $enabled
     * @return Comment
     */
    public function setEnabled($enabled)
    {
        $this->enabled = $enabled;

        return $this;
    }
    /**
    * Get user
    * @return  
    */
    public function getUser()
    {
        return $this->user;
    }
    
    /**
    * Set user
    * @return $this
    */
    public function setUser(User $user)
    {
        $this->user = $user;
        return $this;
    }
    /**
     * Get enabled
     *
     * @return boolean 
     */
    public function getEnabled()
    {
        return $this->enabled;
    }


  	/**
  	* Get video
  	* @return  
  	*/
  	public function getVideo()
  	{
  	    return $this->video;
  	}
  	
  	/**
  	* Set video
  	* @return $this
  	*/
  	public function setVideo($video)
  	{
  	    $this->video = $video;
  	    return $this;
  	}
  
}

Web/src/AppBundle/Form/VideoType.php
<?php
namespace AppBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
class VideoType extends AbstractType
{
   public function buildForm(FormBuilderInterface $builder, array $options)
    {
         $builder->add('title',null,array("label"=>"Title"));
         $builder->add('description',null,array("label"=>"description"));
         $builder->add('enabled',null,array("label"=>"Enabled"));
         $builder->add('comment',null,array("label"=>"Enabled comments"));
         $builder->add('tags',null,array("label"=>"Tags (Keywords)"));

         $builder->add("categories",'entity',
                      array(
                            'class' => 'AppBundle:Category',
                            'expanded' => true,
                            "multiple" => "true",
                            'by_reference' => false
                          )
                      );
         $builder->add("languages",'entity',
                      array(
                            'class' => 'AppBundle:Language',
                            'expanded' => true,
                            "multiple" => "true",
                            'by_reference' => false
                          )
                      );
        $builder->addEventListener(FormEvents::PRE_SET_DATA, function (FormEvent $event) {
            $article = $event->getData();
            $form = $event->getForm();
            if ($article and null !== $article->getId()) {
                 $form->add("file",null,array("label"=>"","required"=>false));
                 $form->add("filevideo",null,array("label"=>"","required"=>false));
            }else{
                 $form->add("file",null,array("label"=>"","required"=>true));
                 $form->add("filevideo",null,array("label"=>"","required"=>true));
            }
        });
        $builder->add('save', 'submit',array("label"=>"save"));
      }
      public function getName()
      {
          return 'Video';
      }
}
?>

Web/src/AppBundle/Controller/VideoController.php
<?php 
namespace AppBundle\Controller;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use AppBundle\Entity\Video;
use MediaBundle\Entity\Media;
use AppBundle\Entity\Day;
use AppBundle\Form\VideoReviewType;
use AppBundle\Form\VideoType;
use AppBundle\Form\VideoTypeUrl;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Serializer\Serializer;
use Symfony\Component\Serializer\Encoder\XmlEncoder;
use Symfony\Component\Serializer\Encoder\JsonEncoder;
use Symfony\Component\Serializer\Normalizer\ObjectNormalizer;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Form\FormError;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\UrlType;

class VideoController extends Controller
{

    public function api_by_followAction(Request $request,$page,$language,$user,$token){
        if ($token!=$this->container->getParameter('token_app')) {
            throw new NotFoundHttpException("Page not found");  
        }
        $nombre=30;
        $em=$this->getDoctrine()->getManager();
        $imagineCacheManager = $this->get('liip_imagine.cache.manager');
        $repository = $em->getRepository('AppBundle:Video');
        if ($language==0) {
            $query = $repository->createQueryBuilder('w')
            ->leftJoin('w.user', 'u')
            ->leftJoin('u.followers', 'f')
            ->where('f.id = '.$user,"w.enabled = true")
            ->addOrderBy('w.created', 'DESC')
            ->addOrderBy('w.id', 'asc')
            ->setFirstResult($nombre*$page)
            ->setMaxResults($nombre)
            ->getQuery();
        }else{
            $query = $repository->createQueryBuilder('w')
            ->leftJoin('w.languages', 'l')
            ->leftJoin('w.user', 'u')
            ->leftJoin('u.followers', 'f')
            ->where('l.id in ('.$language.')','f.id ='.$user,"w.enabled = true")
            ->addOrderBy('w.created', 'DESC')
            ->addOrderBy('w.id', 'asc')
            ->setFirstResult($nombre*$page)
            ->setMaxResults($nombre)
            ->getQuery();  
        }
        $videos = $query->getResult();
        return $this->render('AppBundle:Video:api_all.html.php',array("videos"=>$videos));
    }
    public function api_allAction(Request $request,$page,$order,$language,$token){
        if ($token!=$this->container->getParameter('token_app')) {
            throw new NotFoundHttpException("Page not found");  
        }
        $nombre=30;
        $em=$this->getDoctrine()->getManager();
        $imagineCacheManager = $this->get('liip_imagine.cache.manager');
        $repository = $em->getRepository('AppBundle:Video');


        if ($language==0) {
            $query = $repository->createQueryBuilder('w')
            ->where("w.enabled = true")
            ->addOrderBy('w.'.$order, 'DESC')
            ->addOrderBy('w.id', 'asc')
            ->setFirstResult($nombre*$page)
            ->setMaxResults($nombre)
            ->getQuery();
        }else{
            $query = $repository->createQueryBuilder('w')
            ->leftJoin('w.languages', 'l')
            ->where('l.id in ('.$language.')',"w.enabled = true")
            ->addOrderBy('w.'.$order, 'DESC')
            ->addOrderBy('w.id', 'asc')
            ->setFirstResult($nombre*$page)
            ->setMaxResults($nombre)
            ->getQuery();
        }
        $videos = $query->getResult();
        return $this->render('AppBundle:Video:api_all.html.php',array("videos"=>$videos));
    }
    public function api_by_categoryAction(Request $request,$page,$order,$language,$category,$token){
        if ($token!=$this->container->getParameter('token_app')) {
            throw new NotFoundHttpException("Page not found");  
        }
        $nombre=30;
        $em=$this->getDoctrine()->getManager();
        $imagineCacheManager = $this->get('liip_imagine.cache.manager');
        $repository = $em->getRepository('AppBundle:Video');
        if ($language==0) {
            $query = $repository->createQueryBuilder('w')
            ->leftJoin('w.categories', 'c')
            ->where('c.id = :category',"w.enabled = true")
            ->setParameter('category', $category)
            ->addOrderBy('w.'.$order, 'DESC')
            ->addOrderBy('w.id', 'asc')
            ->setFirstResult($nombre*$page)
            ->setMaxResults($nombre)
            ->getQuery();
        }else{
            $query = $repository->createQueryBuilder('w')
            ->leftJoin('w.languages', 'l')
            ->leftJoin('w.categories', 'c')
            ->where('l.id in ('.$language.')',"w.enabled = true",'c.id = :category')
            
            ->setParameter('category', $category)
            ->addOrderBy('w.'.$order, 'DESC')
            ->addOrderBy('w.id', 'asc')
            ->setFirstResult($nombre*$page)
            ->setMaxResults($nombre)
            ->getQuery();
        }
        $videos = $query->getResult();
        return $this->render('AppBundle:Video:api_all.html.php',array("videos"=>$videos));
    }
    public function api_myAction(Request $request,$page,$user,$token){
        if ($token!=$this->container->getParameter('token_app')) {
            throw new NotFoundHttpException("Page not found");  
        }
        $nombre=30;
        $em=$this->getDoctrine()->getManager();
        $imagineCacheManager = $this->get('liip_imagine.cache.manager');
        $repository = $em->getRepository('AppBundle:Video');
        $query = $repository->createQueryBuilder('w')
        ->leftJoin('w.user', 'c')
        ->where('c.id = :user')
        ->setParameter('user', $user)
        ->addOrderBy('w.created', 'DESC')
        ->addOrderBy('w.id', 'asc')
        ->setFirstResult($nombre*$page)
        ->setMaxResults($nombre)
        ->getQuery();
    
        $videos = $query->getResult();
        return $this->render('AppBundle:Video:api_all.html.php',array("videos"=>$videos));
    }
    public function api_by_queryAction(Request $request,$order,$language,$page,$query,$token){
        if ($token!=$this->container->getParameter('token_app')) {
            throw new NotFoundHttpException("Page not found");  
        }
        $nombre=30;
        $em=$this->getDoctrine()->getManager();
        $imagineCacheManager = $this->get('liip_imagine.cache.manager');
        $repository = $em->getRepository('AppBundle:Video');
        if ($language==0) {
            $query_dql = $repository->createQueryBuilder('w')
            ->where("w.enabled = true","LOWER(w.title) like LOWER('%".$query."%') OR LOWER(w.tags) like LOWER('%".$query."%') ")
            ->addOrderBy('w.'.$order, 'DESC')
            ->addOrderBy('w.id', 'asc')
            ->setFirstResult($nombre*$page)
            ->setMaxResults($nombre)
            ->getQuery();
        }else{
            $language = str_replace("_", ",", $language);
            $query_dql = $repository->createQueryBuilder('w')
            ->leftJoin('w.languages', 'l')
            ->where('l.id in ('.$language.')',"LOWER(w.title) like LOWER('%".$query."%') OR LOWER(w.tags) like LOWER('%".$query."%') ")
            ->addOrderBy('w.'.$order, 'DESC')
            ->addOrderBy('w.id', 'asc')
            ->setFirstResult($nombre*$page)
            ->setMaxResults($nombre)
            ->getQuery();
        }
        $videos = $query_dql->getResult();

        return $this->render('AppBundle:Video:api_all.html.php',array("videos"=>$videos));
    }
    public function api_by_randomAction(Request $request,$language,$token){
        if ($token!=$this->container->getParameter('token_app')) {
            throw new NotFoundHttpException("Page not found");  
        }

        $nombre=30;
        $em=$this->getDoctrine()->getManager();
        $imagineCacheManager = $this->get('liip_imagine.cache.manager');
        $repository = $em->getRepository('AppBundle:Video');


        if ($language==0) {
            $max = sizeof($repository->createQueryBuilder('g')
                ->where("g.enabled = true")
                ->getQuery()->getResult());

            $query = $repository->createQueryBuilder('g')
            ->where("g.enabled = true","g.id >= :rand")
            ->orderBy('g.created', 'DESC')
            ->setParameter('rand',rand(0,$max))
            ->setMaxResults($nombre)
            ->orderBy('g.downloads', 'DESC')
            ->getQuery();
        }else{
            $max = sizeof($repository->createQueryBuilder('g')
                ->leftJoin('g.languages', 'l')
                ->where('l.id in ('.$language.')',"g.enabled = true")
                
                ->getQuery()->getResult());

            $query = $repository->createQueryBuilder('g')
            ->leftJoin('g.languages', 'l')
            ->where('l.id in ('.$language.')',"g.enabled = true","g.id >= :rand")
            
             ->setParameter('rand',rand(0,$max))
            ->orderBy('g.downloads', 'DESC')
            ->setMaxResults($nombre)
            ->getQuery();
        }
        
        $videos = $query->getResult();
        return $this->render('AppBundle:Video:api_all.html.php',array("videos"=>$videos));
    }

    public function addAction(Request $request)
    {
        $video= new Video();
        $form = $this->createForm(new VideoType(),$video);
        $em=$this->getDoctrine()->getManager();

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
          if( $video->getFile()!=null and $video->getFilevideo()!=null){
                $media= new Media();
                $media->setFile($video->getFile());
                $media->setEnabled(true);

Web/src/AppBundle/Resources/views/Video/add.html.twig
{% extends "AppBundle::layout.html.twig" %}
{% block body%}
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-offset-1 col-md-10">
        <div class="card">
          <div class="card-header card-header-icon" data-background-color="rose">
            <i class="material-icons">video_library</i>
          </div>
          <div class="card-content">
            <h4 class="card-title">New Video</h4>
            {{form_start(form)}}
               <div class="form-group label-floating ">
                  <label class="control-label">Video title</label>
                  {{form_widget(form.title,{"attr":{"class":"form-control"}})}}
                  <span class="validate-input">{{form_errors(form.title)}}</span>
              </div>
              <div class="form-group label-floating ">
                  <label class="control-label">Video description</label>
                  {{form_widget(form.description,{"attr":{"class":"form-control"}})}}
                  <span class="validate-input">{{form_errors(form.description)}}</span>
              </div>
               <img src="{{asset("img/image_placeholder.jpg")}}" class="fileinput-preview thumbnail " id="img-preview">
                <div class="fileinput fileinput-new text-center" data-provides="fileinput" style="width: 100%;">
                    <div>
                        <a href="#" class="btn btn-rose btn-round btn-select" style="width: 100%;margin:0px;"><i class="material-icons">image</i> Select Image</a>
                    </div>
                    {{form_widget(form.file,{"attr":{"class":"file-hidden input-file img-selector","style":"   /* display: none; */height: 0px;width: 0px;position: absolute;"}})}}
                    <span class="validate-input">{{form_errors(form.file)}}</span>
               </div>
               <br>
               <video width="100%" style="display:none" controls>
                      <source id="video_here">
                        Your browser does not support HTML5 video.
                     </video>
                      <div class="text-center"  style="width: 100%;">
                         
                          <div>
                              <a href="#" class="btn btn-rose btn-round select-video" style="width: 100%;"><i class="material-icons">videocam</i> Select Video</a>
                          </div>
                          {{form_widget(form.filevideo,{"attr":{"class":"input-video","style":"   /* display: none; */height: 0px;width: 0px;position: absolute;"}})}}
                          <span class="validate-input">{{form_errors(form.filevideo)}}</span>
                     </div>
                      <br>
               <br>
              <div class="">
                    <label>
                      {{form_widget(form.enabled)}}  Enabled
                    </label>
              </div>
              <div class="">
                    <label>
                      {{form_widget(form.comment)}}  Enabled Comment
                    </label>
              </div>
              <br>
              {{form_label(form.categories,null,{label_attr:{"style":"font-size:16px"}})}} :
              <div>
                  <div class="row">
                 {% for field in form.categories %}
                      <label  style="background: #e02d6c;border-radius: 20px;padding: 5px;text-align: center;margin: 10px;color: white;font-weight: bold;padding-left: 20px;padding-right: 20px;">
                          {{ form_widget(field) }} {{ field.vars.label }}
                      </label>
                  {% endfor %}
                  </div>
              </div>
              <br>
              {{form_label(form.languages,null,{label_attr:{"style":"font-size:16px"}})}} :
              <div>
                  <div class="row">
                 {% for field in form.languages %}
                      <label  style="background: #e02d6c;border-radius: 20px;padding: 5px;text-align: center;margin: 10px;color: white;font-weight: bold;padding-left: 20px;padding-right: 20px;">
                          {{ form_widget(field) }} {{ field.vars.label }}
                      </label>
                  {% endfor %}
                  </div>
              </div>
                <div class="form-group label-floating ">
                    <label class="control-label">ringtone tags (Ex:anim,art,hero)</label>
                    <br>
                    {{form_widget(form.tags,{"attr":{"class":"input-tags"}})}}
                    <span class="validate-input">{{form_errors(form.tags)}}</span>
                </div>
                <script>
                $('.input-tags').selectize({
                  persist: false,
                  createOnBlur: true,
                  create: true
                });
                </script>
              <br>
              <span class="pull-right"><a href="{{path("app_video_index")}}" class="btn btn-fill btn-yellow"><i class="material-icons">arrow_back</i> Cancel</a>{{form_widget(form.save,{attr:{"class":"btn btn-fill btn-rose"}})}}</span>
            {{form_end(form)}}
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock%}

Web/src/AppBundle/Resources/views/Video/delete.html.twig
{% extends "AppBundle::layout.html.twig" %}
{% block body%}
<div class="container-fluid">
	<div class="swal2-modal swal2-show" style="display: block; width: 500px; padding: 20px; background: rgb(255, 255, 255); min-height: 332px;" tabindex="-1">
	    <ul class="swal2-progresssteps" style="display: none;"></ul>
	    <div class="swal2-icon swal2-error" style="display: none;"><span class="x-mark"><span class="line left"></span><span class="line right"></span></span>
	    </div>
	    <div class="swal2-icon swal2-question" style="display: none;">?</div>
	    <div class="swal2-icon swal2-warning pulse-warning" style="display: block;">!</div>
	    <div class="swal2-icon swal2-info" style="display: none;">i</div>
	    <div class="swal2-icon swal2-success" style="display: none;"><span class="line tip"></span> <span class="line long"></span>
	        <div class="placeholder"></div>
	        <div class="fix"></div>
	    </div><img class="swal2-image" style="display: none;">
	    <h2>Are you sure</h2>
	    <div class="swal2-content" style="display: block;">Do you really want to delete this image</div>
	    <input class="swal2-input" style="display: none;">
	    <input type="file" class="swal2-file" style="display: none;">
	    <div class="swal2-range" style="display: none;">
	        <output></output>
	        <input type="range">
	    </div>
	    <select class="swal2-select" style="display: none;"></select>
	    <div class="swal2-radio" style="display: none;"></div>
	    <label for="swal2-checkbox" class="swal2-checkbox" style="display: none;">
	        <input type="checkbox">
	    </label>
	    <textarea class="swal2-textarea" style="display: none;"></textarea>
	    <div class="swal2-validationerror" style="display: none;"></div>
	    <hr class="swal2-spacer" style="display: block;">
	    {{form_start(form)}}
              {{form_widget(form.Yes,{"attr":{"class":"swal2-confirm btn btn-success"}})}}
              <a href="{{path("app_video_index")}}" class="swal2-cancel btn btn-danger">Cancel</a>
		{{form_end(form)}}
	</div>
</div>
{% endblock%}

Web/src/AppBundle/Resources/views/Video/view.html.twig
{% extends "AppBundle::layout.html.twig" %}
{% block body%}
<div class="container-fluid">
    <div class="row">
       <div class="col-sm-offset-1 col-md-10">
            <div class="card">
                <div class="card-header card-header-icon" data-background-color="rose">
                    <i class="material-icons">image</i>
                </div>
                <div class="card-content">
                    <h4 class="card-title">{{video.title}}</h4>
                    <p >{{video.description}}</p>
                    <video width="100%" src="{{asset(video.video.link)}}" controls>
                      <source id="video_here">
                        Your browser does not support HTML5 video.
                     </video>
                    <img src="{{asset(video.media.link)}}" class="fileinput-preview thumbnail " id="img-preview">
                    <div style="text-align: center;">
                        <div class="reaction">
                            <span>
                                <img src="{{asset("img/like.png")}}" alt="">
                                <span class="label-reaction">{{video.like}}</span>
                            </span>
                            <span>
                                <img src="{{asset("img/love.png")}}" alt="">
                                <span class="label-reaction">{{video.love}}</span>
                            </span>
                            <span>
                                <img src="{{asset("img/angry.png")}}" alt="">
                                <span class="label-reaction">{{video.angry}}</span>
                            </span>
                            <span>
                                <img src="{{asset("img/haha.png")}}" alt="">
                                <span class="label-reaction">{{video.haha}}</span>
                            </span>
                            <span>
                                <img src="{{asset("img/sad.png")}}" alt="">
                                <span class="label-reaction">{{video.sad}}</span>
                            </span>
                            <span>
                                <img src="{{asset("img/wow.png")}}" alt="">
                                <span class="label-reaction">{{video.woow}}</span>
                            </span>

                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">{% if video.enabled %}
                        <i class="material-icons" style="color:green;float:left">check_circle</i> <span class="check-label">Enabled</span>
                        {% else %}
                        <i class="material-icons" style="color:red;float:left">cancel</i> <span class="check-label">Disabled</span>
                        {% endif %}</div>
                    </div>
                     <div class="row">
                        <div class="col-md-6">{% if video.comment %}
                        <i class="material-icons" style="color:green;float:left">check_circle</i> <span class="check-label">Comment Enabled</span>
                        {% else %}
                        <i class="material-icons" style="color:red;float:left">cancel</i> <span class="check-label">Comment Disabled</span>
                        {% endif %}</div>
                    </div>

                    <div class="row">
                        <div class="col-md-12">
                            <h4>Categories : </h4>
                        </div>
                        <div class="col-md-12" >
                            {% for color in video.categories %}
                                <span class="label label-rose " style="margin:5px;"> <b> {{color.title}} </b></span>  
                            {% endfor %}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <h4>Languages : </h4>
                        </div>
                        <div class="col-md-12" >
                            {% for language in video.languages %}
                                <span class="label label-rose " style="margin:5px;background:#FF5722"> <b> {{language.language}} </b></span>  
                            {% endfor %}
                        </div>
                    </div>
                 </div>
                <div class="card-footer">
                    <div class="price">
                         <div class="wallpaper-logo" style="color:#040303" >
                        {% if video.user.image == "" %}
                            {{video.user.name}}
                        {% else %}
                            <img src="{{video.user.image}}" class="avatar-img" alt=""> 
                        {% endif %}
                         <span>{{video.user.name}}</span>
                     </div>
                    </div>
                    <div class="stats pull-right">
                       <div class="wallpaper-logo"  style="color:#040303" >{{video.created|ago}}</div>
                    </div>
                </div>
            </div>
            <div class="row">
            {% for comment in video.comments %}
                <div class="col-md-6">
                    <ul class="timeline timeline-simple">
                        <li class="timeline-inverted">
                            <div class="timeline-badge danger">
                                <img src="{{comment.user.image}}" class="img-profile">
                            </div>
                            <div class="timeline-panel">
                                <div class="timeline-heading">
                                    <a href="{{path("user_user_edit",{id:comment.user.id})}}" title="">
                                        <span class="label label-danger">{{comment.user.name}}</span>
                                    </a>
                                    <span class="pull-right" >
                                        <a href="{{path("app_comment_delete",{id:comment.id,"video":"true"})}}"  rel="tooltip" data-placement="bottom" title="" data-original-title="Delete">
                                            <i class="material-icons" style="color:red">delete</i>
                                        </a>
                                        {% if comment.enabled %}
                                            <a href="{{path("app_comment_hide",{id:comment.id})}}"  rel="tooltip" data-placement="bottom" title="" data-original-title="Hide">
                                                 <i class="material-icons">visibility_off</i>
                                            </a>
                                        {% else %}                                      
                                            <a href="{{path("app_comment_hide",{id:comment.id})}}"  rel="tooltip" data-placement="bottom" title="" data-original-title="Show">
                                                 <i class="material-icons">remove_red_eye</i>
                                            </a>
                                        {% endif %}
                                    </span>
                                </div>
                                <div class="timeline-body">
                                    <p>{{comment.contentclear}}</p>
                                </div>
                                <small class="pull-right label label-rose">
                                     <span>{{comment.created|ago}}</span>
                                </small>
                            </div>
                        </li>
                       
                    </ul>
                </div>
                {% else %}
                <div class="col-md-12" >
                    <div class="card"  style="margin-top: 0px;">
                        <div class="card-content">
                            <center><img src="{{asset("img/bg_empty.png")}}"  style="width: auto !important;" =""></center>
                            <br>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock%}